### ISSUE TITLE
About Fan Speed

### ISSUE THREAD

**Issue by zty199** [1alessandro1/HP-Pavilion-CE2072NL-macOS#1]
My Laptop is HP Pavilion 15-cb073tx, and I got same ERAM part in DSDT as yours......(Actually most HP Pavilion series laptops produced before 2018 have similar(or completely same) DSDT, especially ERAM parts......)

I thought that there is a origin method in DSDT called **FRSP**, which is related to fan speed.

This method is in **_TZ.TZ01**, and you can simply modify this method to get a number between 2000(±50)~3500(±50), and this number increases correctly when temperature goes up.
Do you really think **RPM1** and **RPM2** are not related to fan rpm?

Here is my SSDT......

```
//Maybe there are still mistakes...     By zty199
DefinitionBlock ("", "SSDT", 2, "ACDT", "FANS", 0)
{
    External (_SB_.PCI0.LPCB.EC.RPM1, FieldUnitObj)
    External (_SB_.PCI0.LPCB.EC.RPM2, FieldUnitObj)
    Scope(\)
    {
        Device (FANS)
        {
            Name (_HID, EisaId ("APP0111"))  // _HID: Hardware ID
            Name (_CID, "monitor")  // _CID: Compatible ID
            
            Method (FAN0, 1, NotSerialized)
            {
                Local0 = \_SB.PCI0.LPCB.EC.RPM1
                Local1 = \_SB.PCI0.LPCB.EC.RPM2
                Local1 <<= 0x08
                Local0 |= Local1
                Return (Local0)
            }
            
            Method (_STA, 0, NotSerialized)  // _STA: Status
            {
                If (_OSI ("Darwin"))
                {
                    Return (0x0F)
                }
                Else
                {
                    Return (Zero)
                }
            }
        }
    }
}
```

Once I use this SSDT with FakeSMC to show FAN Speed, so is there any way to make this work in SMCSuperIO?

(Sorry for my poor English......Hope you can understand what I'm trying to say......)

**Comment by 1alessandro1** [comment]
Hi, in this laptop fan speed is monitored by the chip ITE 8987 (the datasheet is attached [here](https://github.com/acidanthera/bugtracker/files/6190084/IT8987_B_V0.3.1_102513.pdf)) and the only way for me to implement fan reading on this laptop is though the EC device, as discussed in this issue, and in this comment:

https://github.com/acidanthera/bugtracker/issues/395#issuecomment-808728953


And here's a screenshot of the fan headers present in my laptop motherboard (just 1)

https://github.com/acidanthera/bugtracker/issues/395#issuecomment-808756416

So if you have my same chip (you can check that by disassembling your laptop or by building `superiotool` for Linux from coreboot repo) you do not need any SSDT, but instead latest build of SMCSuperIO from dortania.github.io/builds, [here is the direct link](https://github.com/dortania/build-repo/releases/download/VirtualSMC-f11bdfc/VirtualSMC-1.2.3-RELEASE.zip) and try to load [this](https://github.com/1alessandro1/HP-Pavilion-CE2072NL-macOS/blob/d29ecdec198cbff4514d2257e5bf958b5d5731a6/EFI/OC/config.plist#L524-L536) deviceproperty for the LPCB bus:

```
			<key>PciRoot(0x0)/Pci(0x1f,0x0)</key>
			<dict>
				<key>ec-device</key>
				<string>generic</string>
				<key>fan-count</key>
				<data>AQAAAA==</data>
				<key>fan0-addr</key>
				<data>wwAAAA==</data>
				<key>fan0-big</key>
				<data>AAAAAA==</data>
				<key>fan0-size</key>
				<data>AgAAAA==</data>
			</dict>
```

However your fan offset (0xC3 for me) could be different, attach your SysReport as I can check from there if the `ERAM` field is exactly the same as mine.

Please use [this standard OC DEBUG EFI folder](https://github.com/utopia-team/opencore-debug/releases/latest) to provide the neccessary information about your firmware, just copy that to an ESP and reach the boot picker, then you can shut down by pressing the power button or by pressing TAB to reach the Shutdown button in OC picker, as your dump is collected right before loading OpenCore boot menu.

**Comment by zty199** [comment]
Sorry for bothering you again...... I disassembled my laptop this morning and I found my chip is IT8987E, which should be the same one as yours?

![IMG_2440](https://user-images.githubusercontent.com/46324746/114841479-77b2cc00-9e0a-11eb-8f07-32c112e35c7c.jpg)

But on my laptop motherboard, there are two fan headers present.

![IMG_2442](https://user-images.githubusercontent.com/46324746/114841668-b052a580-9e0a-11eb-90bb-6026e02b67f4.jpg)

I did try your fan offset 0xC3 last night, but the number is between 180~230, and only shows up when temperature is above 70. I'm not sure if this is correct......

And here is my SysReport, hope this is useful......

[SysReport.zip](https://github.com/1alessandro1/HP-Pavilion-CE2072NL-macOS/files/6316531/SysReport.zip)

**Comment by 1alessandro1** [comment]
Your ACPI are very different than mine (mine is an HP 84BB, yours is 836B), so I think the 0xC3 is most likely wrong. Maybe this weekend I'll post how to find the correct offset for your fan

**Comment by 1alessandro1** [comment]
These are the steps to find the correct offset for your firmware:

- Download Lilu and VirtualSMC DEBUG from acidanthera
- Add the following boot args to your config.plist: `-v keepsyms=1 debug=0x100 -liludbgall -liludump=120 -vsmcdbg`
- Boot the system with the changes made above, and attach Lilu log which can be found on `/var/log` 120 seconds after the system has been powered on.

**Comment by 1alessandro1** [comment]
After that, you'll have to revert back all the changes mentioned in the message above, and:

- Enter your BIOS and *disable* `Fan Always On` setting
- Keep only the latest SMCSuperIO debug from latest VirtualSMC [here](https://github.com/dortania/build-repo/releases/download/VirtualSMC-104705c/VirtualSMC-1.2.3-DEBUG.zip)
- Add the following boot args to your config.plist:  `-v ssioec=debug ssiowndsz=5 ssiownd=0x00`

Once you've done that, install MacsFanControl and you'll find 5 different values. 

Patience is very important now, as you have to cycle though the offsets from 0x00 to 0xFF (51 reboots) until you find a direct correspondence between FAN values different from `0` when FAN is spinning (hearable noise) and FAN values which go to `0` when fan stops under `50 °C`, specifically:

- Open macsfancontrol, check all the 5 values reported, as long as the values keep boucing around when the FAN is OFF (from what you hear) then your offset is wrong. Add +0x05 to the previous value counting from 0x00, or check my [doc](https://github.com/1alessandro1/HP-Pavilion-CE2072NL-macOS/blob/main/Misc/EC-ITE8987/Fan-Hunting.md#results) for all the values already calculated
- Values from MacsFancontrol are going to jump around and are incorrect, but the only value which stays correct is when fan stops, going to zero. You know you found the correct offset when macsfancontrol reports `0 rpm` immediately once you hear that your FAN has stopped, (you don't hear it spinning anymore). 
 

Few exaples of what you need to do from a reboot to another:

- 1st try: `-v ssioec=debug ssiowndsz=5 ssiownd=0x00`
- 2nd try: `-v ssioec=debug ssiowndsz=5 ssiownd=0x05`
- 3rd try: `-v ssioec=debug ssiowndsz=5 ssiownd=0x0A`
- 4th try: `-v ssioec=debug ssiowndsz=5 ssiownd=0x0F`

to 0xFF. I've already made a table with some calculations [here](https://github.com/1alessandro1/HP-Pavilion-CE2072NL-macOS/blob/main/Misc/EC-ITE8987/Fan-Hunting.md#results) so the offsets have been already written, just change the hex value and check fan status from load. 


**Note**: Correct fan speed will NOT be reported. Your focus is to find only the direct correspondence from working fan to steady fan when load comes in, and then comes out.

For any doubts, write them here, I'll try to respond if I can

**Comment by 1alessandro1** [comment]
I suggest to check `0xC3` offset first, maybe the guys at [HP](https://hp.com) were nice to us and kept the offset for the different models

**Comment by zty199** [comment]
After about 3 hours suffering..... I found that I was wasting my time......

I tested all addresses in EC RAM, and only 4 seem to be related with fan speed: **0xB2, 0xB3** (which I already known), 0xC3, 0xC4.

However, 0xC3 and 0xC4 didn't act as you described, they are still zero when fans start to spin at low speed (Temperature is above 65 ℃). When fans speed up (I can hear more noise), they are not zero; And when temperature drops, they will be zero when fan is still spinning at low speed.

0xB2 and 0xB3 act as you described precisely, when fans are stopped, they are zero; when fans start to spin, they are not.

So Here is the problem...... For now SMCSuperIO can only read one address at a time, how can I get correct number of fan speed which is spilt into two different addresses? (FAN Speed = 0xB3 * 256 + 0XB2)

And here is my test result, I'm not sure if it is absolutely correct......
[FanOffsetTest.txt](https://github.com/1alessandro1/HP-Pavilion-CE2072NL-macOS/files/6353192/FanOffsetTest.txt)

**Comment by 1alessandro1** [comment]
> So Here is the problem...... For now SMCSuperIO can only read one address at a time, how can I get correct number of fan speed which is spilt into two different addresses? (FAN Speed = 0xB3 * 256 + 0XB2)
And here is my test result, I'm not sure if it is absolutely correct......
FanOffsetTest.txt

I suggest to forward this whole text to https://github.com/acidanthera/bugtracker/issues/395 and wait vit9696 to implement that in smcsuperio

Ping him with a @ I'll follow the issue there

**Comment by zty199** [comment]
Thanks for your help! According to vit9696's explaination, now I got correct value of fan speed for both two connectors!

And you are right about fan address...... RPM1 and RPM2 (0xB2 and 0xB3) is actually another fan connector which is not on your motherboard......XD...... 

And I believe that you can set
```
fan0-size    data    02000000
fan0-big    data    01000000
fan0-addr    data    C4000000
```
to get fan speed? The value should be between 2000-3500?

**Comment by 1alessandro1** [comment]
Sorry for late reply, I've been busy at work.

> And I believe that you can set
fan0-size    data    02000000
fan0-big    data    01000000
fan0-addr    data    C4000000

yes, tested now and it works

> to get fan speed? The value should be between 2000-3500?

yes the fan starts at 2800 and then goes high to 3500ish with moderate load

**Comment by 1alessandro1** [comment]
With very high load, `libx265` can spike the CPU to 90 C while IPG is in the background in full load all threads AVX

![image](https://user-images.githubusercontent.com/46293832/115761620-d2b46800-a3a2-11eb-9f5e-206387209405.png)

**Comment by zty199** [comment]
Sorry for wasting your time...... I made a big mistake yesterday about big endian......

For example, when I use big endian from 0xC4, the value I get is simply 0xC4 * 256 (because 0xC5 is **zero** coincidentally), so the value seems to be right, but it is a fixed number. (Because the real number should be 0xC4 * 256 **+ 0xC3**, and **0xC3** in this situation is missed......)

I'm truely sorry...... Your device-property was right, I will fix that......
