### ISSUE TITLE
Does the macOS Powerchime work for you

### ISSUE THREAD

**Issue by Human79** [1alessandro1/HP-Pavilion-CE2072NL-macOS#2]
Does the macOS Powerchime (the sound when you plug in the charger) work for you? It can only be heard using headphone on my laptop. However, the headphone port is not detected until I plug it in.
Regards.

**Comment by 1alessandro1** [comment]
> Does the macOS Powerchime (the sound when you plug in the charger) work for you?

Yes, which layout-id are you using?

>  However, the headphone port is not detected until I plug it in.

I have the same behaviour here:

 
![image](https://user-images.githubusercontent.com/46293832/121699245-0e300080-cacf-11eb-803e-efdf9a997ca6.png)

**Comment by Human79** [comment]
Hey there
Sorry for replying late. I realized we may not have the same codec. What is your codec?
Thanks.

**Comment by 1alessandro1** [comment]
From master you can see that under the HDEF path I'm using layout-id = 13 (0D000000 in hex)

```xml
PciRoot(0x0)/Pci(0x1F,0x3) 
      <key>layout-id</key>
      <data>DQAAAA==</data>
```

**Comment by Human79** [comment]
I am also using layout-id 13. It doesn't work for me though.
