### ISSUE TITLE
HP fan control

### ISSUE THREAD

**Issue by Overc1ocker** [1alessandro1/HP-Pavilion-CE2072NL-macOS#3]
Hello! So I have noticed that we finally have EC based fan control in MacOS via SMCsuperio. I have decided to try to add fan control to a HP Notebook 15 laptop. Here's what I got so far. 

SuperIO model number: KB9022Q by ENE

SuperIO read register automatic fan: 17 (0x11) (Gets set to 0 if manual fan control is used)

--Enable--
This system requires you to enable fan control override mode

SuperIO Fctl enable register: 21 (0x15) Set this to 0x1 for manual fan control (must be set again after sleep/restart)

---Fan control----

SuperIO Write register: 25 (0x19) Accepts a value from 0-55, set this to FF for auto control 

SuperIO reserved speeds: (while increasing fan speeds from 0-55, these speeds ramp the fan down a little) 26,31,38,43,47,53

My questions:
--Important--
-This system requires a enable register be written when controlling the fans, both on startup and after sleep. Is there a way this can be done via the config.plist?

--nice to haves--
-Is there a way that the read register can be switched from 0x19 to 0x11 when a fan is automatic?

-Can we omit the above speeds for a smooth fan control experience?

**Comment by 1alessandro1** [comment]
I suggest to post this on https://github.com/acidanthera/bugtracker/issues/395

**Comment by 1alessandro1** [comment]
@Overc1ocker try this:

https://github.com/zhen-zen/YogaSMC/pull/147
